//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSTO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSTO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Google. Internal exception contains last error reported during attempt to connect to Google.
        /// </summary>
        internal static string Error_GoogleConnectionFailure {
            get {
                return ResourceManager.GetString("Error_GoogleConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action on the item failed:.
        /// </summary>
        internal static string Error_ItemSynchronizationFailure {
            get {
                return ResourceManager.GetString("Error_ItemSynchronizationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Outlook. Internal exception contains last error reported during attempt to connect to Outlook.
        /// </summary>
        internal static string Error_OutlookConnectionFailure {
            get {
                return ResourceManager.GetString("Error_OutlookConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval for yearly recurrence pattern is not supported by this version of Outlook. This item won&apos;t be synchronized.
        /// </summary>
        internal static string Error_WrongYearlyInterval {
            get {
                return ResourceManager.GetString("Error_WrongYearlyInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching item &apos;{0}&apos; is found outside of range.
        /// </summary>
        internal static string Info_ItemOutsideOfRange {
            get {
                return ResourceManager.GetString("Info_ItemOutsideOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google item &apos;{0}&apos; has {1} reminders whilst Outlook can have only 1. Reminders won&apos;t be compared for this item.
        /// </summary>
        internal static string Info_MultipleReminders {
            get {
                return ResourceManager.GetString("Info_MultipleReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;
        ///          loadImage=&quot;LoadImage&quot;
        ///          onLoad=&quot;LoadRibbon&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab id=&quot;Synchronize&quot; label=&quot;Synchronize&quot;&gt;
        ///        &lt;group id=&quot;GoogleGroup&quot; label=&quot;Google&quot;&gt;
        ///          &lt;toggleButton id=&quot;SyncGoogleToggleButton&quot; label=&quot;Google&quot; size=&quot;large&quot; onAction=&quot;SyncGoogle&quot; getPressed=&quot;GetPressed&quot; image=&quot;Logo&quot; /&gt;
        ///          &lt;button id=&quot;FolderButton&quot; label=&quot;Folder to synchronize&quot; siz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
    }
}
