//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AttemptsAmount {
            get {
                return ((int)(this["AttemptsAmount"]));
            }
            set {
                this["AttemptsAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoogleItemID")]
        public string ExtendedPropertyName_GoogleIDInOutlookItem {
            get {
                return ((string)(this["ExtendedPropertyName_GoogleIDInOutlookItem"]));
            }
            set {
                this["ExtendedPropertyName_GoogleIDInOutlookItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce")]
        public string Registry_Key_Autorun {
            get {
                return ((string)(this["Registry_Key_Autorun"]));
            }
            set {
                this["Registry_Key_Autorun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\Rasoft\\GoogleOutlookSyncAddIn")]
        public string ApplicationRegistryKey {
            get {
                return ((string)(this["ApplicationRegistryKey"]));
            }
            set {
                this["ApplicationRegistryKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalendarName")]
        public string CalendarSettings_CalendarName {
            get {
                return ((string)(this["CalendarSettings_CalendarName"]));
            }
            set {
                this["CalendarSettings_CalendarName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalendarDaysBefore")]
        public string CalendarSettings_RangeBefore {
            get {
                return ((string)(this["CalendarSettings_RangeBefore"]));
            }
            set {
                this["CalendarSettings_RangeBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalendarDaysAfter")]
        public string CalendarSettings_RangeAfter {
            get {
                return ((string)(this["CalendarSettings_RangeAfter"]));
            }
            set {
                this["CalendarSettings_RangeAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Privacy")]
        public string Privacy {
            get {
                return ((string)(this["Privacy"]));
            }
            set {
                this["Privacy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OutlookFolderID")]
        public string RegistryKey_OutlookFolderID {
            get {
                return ((string)(this["RegistryKey_OutlookFolderID"]));
            }
            set {
                this["RegistryKey_OutlookFolderID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SynchronizationInterval")]
        public string RegistryKey_SyncInterval {
            get {
                return ((string)(this["RegistryKey_SyncInterval"]));
            }
            set {
                this["RegistryKey_SyncInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoogleColorID")]
        public string RegistryKey_GoogleColorID {
            get {
                return ((string)(this["RegistryKey_GoogleColorID"]));
            }
            set {
                this["RegistryKey_GoogleColorID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OutlookCategoryName")]
        public string RegistryKey_OutlookCategoryName {
            get {
                return ((string)(this["RegistryKey_OutlookCategoryName"]));
            }
            set {
                this["RegistryKey_OutlookCategoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoogleAccount")]
        public string RegistryKey_GoogleAccount {
            get {
                return ((string)(this["RegistryKey_GoogleAccount"]));
            }
            set {
                this["RegistryKey_GoogleAccount"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("626714144907-rl6a257nriprt840547j39t45t9qmafj.apps.googleusercontent.com")]
        public string GoogleAPI_ClientID {
            get {
                return ((string)(this["GoogleAPI_ClientID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mmS0N0blRMFMKilskIE7SJa0")]
        public string GoogleAPI_ClientSecret {
            get {
                return ((string)(this["GoogleAPI_ClientSecret"]));
            }
        }
    }
}
